<a href="https://colab.research.google.com/github/husnainsr/Amazon-Web-Scrapper/blob/master/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Agenda is to Learn and explore different operations in tensors

In [1]:
import torch


In [5]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Reshape and View

In [6]:
# What if we want reshape the tensor? Well we can do that in tensor
# from 1D 10 to 2,5
## Note we cannot change it beyond the size if we multiply rows x cols it should be equal to the 1D tensor size
my_torch = my_torch.reshape(2,5)
print(my_torch)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [9]:
# lets say we do not know the size of our 1D tensor then we can use -1
second_torch = torch.arange(10)
print(second_torch)

# the first parameter should be divisible by the 1D tensor size otherwise it will give error
second_torch = second_torch.reshape(5,-1)
print(second_torch)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


## View is similar to Reshape
### Then whats the difference?
Well view shares the same underline data which means if is change the view data it will also changed the previous tensor to whom it is origniated where as reshape does not do this it creates a seperate copy


In [14]:
simple_tensor = torch.arange(6)
print(simple_tensor)

tensor([0, 1, 2, 3, 4, 5])


In [16]:
view_tensor = simple_tensor.view(2,3)
print(view_tensor)

tensor([[0, 1, 2],
        [3, 4, 5]])


Now if i changed the simple_view it will also changed the simple_tesnor lets try this out

In [20]:
view_tensor[0][0]=100
print("View tensor after Modifying")
print(view_tensor)

print("Orignal tensor")
print(simple_tensor)

View tensor after Modifying
tensor([[100,   1,   2],
        [  3,   4,   5]])
Orignal tensor
tensor([100,   1,   2,   3,   4,   5])
